config/routes.rb
GameStore::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  
  resources :platforms
  
  resources :consoles
  
  resources :games
  
  resources :accessories

  resources :online_services
  
  get '/login/', to: 'home#login'
  
  get '/cart/', to: 'home#cart'
  
  root 'home#index'
  
  

  

end

app/models/console.rb
class Console < ActiveRecord::Base
  
  def slug
    name.downcase.gsub(" ", "-")
  end
  
  def to_param
    slug
  end
  
end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
  before_action :set_console, only: [:show, :edit, :update, :destroy]

  # GET /consoles
  # GET /consoles.json
  def index
    @consoles = Console.all
  end

  # GET /consoles/playstation-4
  # GET /consoles/playstation-4.json
  def show
    
    @console = Console.find_by_slug(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
    
  end

  # GET /consoles/new
  def new
    @console = Console.new
  end

  # GET /consoles/1/edit
  def edit
  end

  # POST /consoles
  # POST /consoles.json
  def create
    @console = Console.new(console_params)

    respond_to do |format|
      if @console.save
        format.html { redirect_to @console, notice: 'Console was successfully created.' }
        format.json { render action: 'show', status: :created, location: @console }
      else
        format.html { render action: 'new' }
        format.json { render json: @console.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consoles/1
  # PATCH/PUT /consoles/1.json
  def update
    respond_to do |format|
      if @console.update(console_params)
        format.html { redirect_to @console, notice: 'Console was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @console.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consoles/1
  # DELETE /consoles/1.json
  def destroy
    @console.destroy
    respond_to do |format|
      format.html { redirect_to consoles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_console
      @console = Console.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def console_params
      params.require(:console).permit(:name, :abbr, :company, :release_date, :image_path)
    end
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/views/consoles/_form.html.erb
<%= form_for(@console) do |f| %>
  <% if @console.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@console.errors.count, "error") %> prohibited this console from being saved:</h2>

      <ul>
      <% @console.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbr %><br>
    <%= f.text_field :abbr %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.text_field :release_date %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br>
    <%= f.text_field :image_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consoles/edit.html.erb
<h1>Editing console</h1>

<%= render 'form' %>

<%= link_to 'Show', @console %> |
<%= link_to 'Back', consoles_path %>

app/views/consoles/index.html.erb
<h1>Listing consoles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbr</th>
      <th>Company</th>
      <th>Release date</th>
      <th>Image path</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @consoles.each do |console| %>
      <tr>
        <td><%= console.name %></td>
        <td><%= console.abbr %></td>
        <td><%= console.company %></td>
        <td><%= console.release_date %></td>
        <td><%= console.image_path %></td>
        <td><%= link_to 'Show', console %></td>
        <td><%= link_to 'Edit', edit_console_path(console) %></td>
        <td><%= link_to 'Destroy', console, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Console', new_console_path %>

app/views/consoles/new.html.erb
<h1>New console</h1>

<%= render 'form' %>

<%= link_to 'Back', consoles_path %>

app/views/consoles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @console.name %>
</p>

<p>
  <strong>Abbr:</strong>
  <%= @console.abbr %>
</p>

<p>
  <strong>Company:</strong>
  <%= @console.company %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @console.release_date %>
</p>

<p>
  <strong>Image path:</strong>
  <%= @console.image_path %>
</p>

<%= link_to 'Edit', edit_console_path(@console) %> |
<%= link_to 'Back', consoles_path %>