config/routes.rb
GameStore::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  
  resources :platforms
  
  resources :consoles
  
  resources :games
  
  resources :accessories

  resources :online_services
  
  get '/login/', to: 'home#login'
  
  get '/cart/', to: 'home#cart'
  
  root 'home#index'
  
  

  

end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  # TODO: Index should only be accessed by admin, and any edit, add, destroy should be done by admin

  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all
  end

  # GET /platforms/playstation-4
  # GET /platforms/1.json
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(platform_params)

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render action: 'show', status: :created, location: @platform }
      else
        format.html { render action: 'new' }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1
  # PATCH/PUT /platforms/1.json
  def update
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform.destroy
    respond_to do |format|
      format.html { redirect_to platforms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_params
      params.require(:platform).permit(:name, :abbr)
    end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.erb
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbr %><br>
    <%= f.text_field :abbr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<h1>Editing platform</h1>

<%= render 'form' %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<h1>Listing platforms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbr</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @platforms.each do |platform| %>
      <tr>
        <td><%= platform.name %></td>
        <td><%= platform.abbr %></td>
        <td><%= link_to 'Show', platform %></td>
        <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
        <td><%= link_to 'Destroy', platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Platform', new_platform_path %>

app/views/platforms/new.html.erb
<h1>New platform</h1>

<%= render 'form' %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<div class="platforms_page">

	<h2><%= @platform.name %></h2>
	
	<div id="platform_products_nav" class="row">
		
		<!-- TODO: Center -->
		<ul id="product_tabs" class="nav nav-tabs" role="tablist">
		  <li class="active"><a href="#preorders" role="tab" data-toggle="tab">Preorder</a></li>
		  <li><a href="#consoles" role="tab" data-toggle="tab">Consoles</a></li>
		  <li><a href="#games" role="tab" data-toggle="tab">Games</a></li>
		  <li><a href="#accessories" role="tab" data-toggle="tab">Accessories</a></li>
		  <li><a href="#online_services" role="tab" data-toggle="tab">PSN</a></li> <!-- TODO: Change based on platform -->
		</ul>
		
		<div id="product_display" class="tab-content">
			<div class="tab-pane active" id="preorders"><%= link_to "Preorders", games_path %></div>
			<div class="tab-pane" id="consoles"><%= link_to "Consoles", consoles_path %></div>
			<div class="tab-pane" id="games"><%= link_to "Games", games_path %></div>
			<div class="tab-pane" id="accessories"><%= link_to "Accessories", accessories_path %></div> <!-- TODO: Change to Accessories -->
			<div class="tab-pane" id="online_services"><%= link_to "Online Service", online_services_path %></div>
		</div>	
		
	</div>
	
	<h3>Best Selling <%= @platform.abbr %> Games</h3>
	
	<div class="row">
		
	  <div class="col-xs-12 col-md-1 col-md-offset-1">
		    <a href="#" class="thumbnail">Game</a>
      </div>
	  
	  <% 8.times do %>
		  <div class="col-xs-12 col-md-1">
		    <a href="#" class="thumbnail">Game</a>
		  </div>
	  <% end %>
	  
	  <div class="col-xs-12 col-md-1">
		    <a href="#" class="thumbnail">Game</a>
      </div>
	  
	  <div class="col-xs-12 col-md-1">

      </div>
	  
	</div>
	
	<div class="admin center">
		<%= link_to 'Edit', edit_platform_path(@platform) %> |
		<%= link_to 'Back', platforms_path %>
	</div>

</div>