config/routes.rb
GameStore::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  
  resources :platforms
  
  resources :consoles
  
  resources :games
  
  resources :accessories

  resources :online_services
  
  get '/login/', to: 'home#login'
  
  get '/cart/', to: 'home#cart'
  
  root 'home#index'
  
  

  

end

app/models/online_service.rb
class OnlineService < ActiveRecord::Base
end

app/controllers/online_services_controller.rb
class OnlineServicesController < ApplicationController
  before_action :set_online_service, only: [:show, :edit, :update, :destroy]

  # GET /online_services
  # GET /online_services.json
  def index
    @online_services = OnlineService.all
  end

  # GET /online_services/1
  # GET /online_services/1.json
  def show
  end

  # GET /online_services/new
  def new
    @online_service = OnlineService.new
  end

  # GET /online_services/1/edit
  def edit
  end

  # POST /online_services
  # POST /online_services.json
  def create
    @online_service = OnlineService.new(online_service_params)

    respond_to do |format|
      if @online_service.save
        format.html { redirect_to @online_service, notice: 'Online service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @online_service }
      else
        format.html { render action: 'new' }
        format.json { render json: @online_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /online_services/1
  # PATCH/PUT /online_services/1.json
  def update
    respond_to do |format|
      if @online_service.update(online_service_params)
        format.html { redirect_to @online_service, notice: 'Online service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @online_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /online_services/1
  # DELETE /online_services/1.json
  def destroy
    @online_service.destroy
    respond_to do |format|
      format.html { redirect_to online_services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_online_service
      @online_service = OnlineService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def online_service_params
      params.require(:online_service).permit(:name, :platform, :price, :quantity, :emailed, :instore)
    end
end

app/helpers/online_services_helper.rb
module OnlineServicesHelper
end

app/views/online_services/_form.html.erb
<%= form_for(@online_service) do |f| %>
  <% if @online_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@online_service.errors.count, "error") %> prohibited this online_service from being saved:</h2>

      <ul>
      <% @online_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :platform %><br>
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :emailed %><br>
    <%= f.check_box :emailed %>
  </div>
  <div class="field">
    <%= f.label :instore %><br>
    <%= f.check_box :instore %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/online_services/edit.html.erb
<h1>Editing online_service</h1>

<%= render 'form' %>

<%= link_to 'Show', @online_service %> |
<%= link_to 'Back', online_services_path %>

app/views/online_services/index.html.erb
<h1>Listing online_services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Platform</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Emailed</th>
      <th>Instore</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @online_services.each do |online_service| %>
      <tr>
        <td><%= online_service.name %></td>
        <td><%= online_service.platform %></td>
        <td><%= online_service.price %></td>
        <td><%= online_service.quantity %></td>
        <td><%= online_service.emailed %></td>
        <td><%= online_service.instore %></td>
        <td><%= link_to 'Show', online_service %></td>
        <td><%= link_to 'Edit', edit_online_service_path(online_service) %></td>
        <td><%= link_to 'Destroy', online_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Online service', new_online_service_path %>

app/views/online_services/new.html.erb
<h1>New online_service</h1>

<%= render 'form' %>

<%= link_to 'Back', online_services_path %>

app/views/online_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @online_service.name %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @online_service.platform %>
</p>

<p>
  <strong>Price:</strong>
  <%= @online_service.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @online_service.quantity %>
</p>

<p>
  <strong>Emailed:</strong>
  <%= @online_service.emailed %>
</p>

<p>
  <strong>Instore:</strong>
  <%= @online_service.instore %>
</p>

<%= link_to 'Edit', edit_online_service_path(@online_service) %> |
<%= link_to 'Back', online_services_path %>