config/routes.rb
GameStore::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  
  resources :platforms
  
  resources :consoles
  
  resources :games
  
  resources :accessories

  resources :online_services
  
  get '/login/', to: 'home#login'
  
  get '/cart/', to: 'home#cart'
  
  root 'home#index'
  
  

  

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :platform, :edition, :price, :quantity, :release_date, :instore, :online, :digital, :preorder)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :platform %><br>
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :edition %><br>
    <%= f.text_field :edition %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.text_field :release_date %>
  </div>
  <div class="field">
    <%= f.label :instore %><br>
    <%= f.check_box :instore %>
  </div>
  <div class="field">
    <%= f.label :online %><br>
    <%= f.check_box :online %>
  </div>
  <div class="field">
    <%= f.label :digital %><br>
    <%= f.check_box :digital %>
  </div>
  <div class="field">
    <%= f.label :preorder %><br>
    <%= f.check_box :preorder %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Platform</th>
      <th>Edition</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Release date</th>
      <th>Instore</th>
      <th>Online</th>
      <th>Digital</th>
      <th>Preorder</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.platform %></td>
        <td><%= game.edition %></td>
        <td><%= game.price %></td>
        <td><%= game.quantity %></td>
        <td><%= game.release_date %></td>
        <td><%= game.instore %></td>
        <td><%= game.online %></td>
        <td><%= game.digital %></td>
        <td><%= game.preorder %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @game.platform %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @game.edition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @game.quantity %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @game.release_date %>
</p>

<p>
  <strong>Instore:</strong>
  <%= @game.instore %>
</p>

<p>
  <strong>Online:</strong>
  <%= @game.online %>
</p>

<p>
  <strong>Digital:</strong>
  <%= @game.digital %>
</p>

<p>
  <strong>Preorder:</strong>
  <%= @game.preorder %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>